# Generated by Django 5.0 on 2023-12-25 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centre',
            fields=[
                ('codeC', models.AutoField(primary_key=True, serialize=False)),
                ('nomC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('codeCl', models.AutoField(primary_key=True, serialize=False)),
                ('nomCl', models.CharField(max_length=50)),
                ('prenomCl', models.CharField(max_length=50)),
                ('adresseCl', models.CharField(max_length=50)),
                ('telephoneCl', models.CharField(max_length=10)),
                ('credit', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('codeF', models.AutoField(primary_key=True, serialize=False)),
                ('nomF', models.CharField(max_length=50)),
                ('prenomF', models.CharField(max_length=50)),
                ('adresseF', models.CharField(max_length=50)),
                ('telephoneF', models.CharField(max_length=10)),
                ('solde', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('codeP', models.AutoField(primary_key=True, serialize=False)),
                ('nomP', models.CharField(max_length=50)),
                ('prix_achat', models.FloatField(max_length=10)),
                ('prix_vente', models.FloatField(max_length=10)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employe',
            fields=[
                ('codeE', models.AutoField(primary_key=True, serialize=False)),
                ('nomE', models.CharField(max_length=50)),
                ('prenomE', models.CharField(max_length=50)),
                ('adresseE', models.CharField(max_length=50)),
                ('telephoneE', models.CharField(max_length=10)),
                ('salaire_jour', models.FloatField(max_length=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.centre')),
            ],
        ),
    ]
