# Generated by Django 5.0 on 2023-12-25 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commande',
            fields=[
                ('codeCom', models.AutoField(primary_key=True, serialize=False)),
                ('dateCom', models.DateTimeField(default=datetime.datetime.now)),
                ('produits', models.ManyToManyField(related_name='commande', to='app.produit')),
            ],
        ),
    ]
