# Generated by Django 5.0 on 2023-12-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='matierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomM', models.CharField(max_length=50)),
                ('prix_achatM', models.FloatField(max_length=10)),
                ('prix_venteM', models.FloatField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='centre',
            name='codeC',
        ),
        migrations.RemoveField(
            model_name='client',
            name='codeCl',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='codeE',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='codeF',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='codeP',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
        migrations.AddField(
            model_name='centre',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centre',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employe'),
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='commande',
        ),
    ]
