# Generated by Django 5.0 on 2023-12-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_matierepremiere_remove_centre_codec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='responsable',
        ),
        migrations.AddField(
            model_name='employe',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.centre'),
            preserve_default=False,
        ),
    ]
