# Generated by Django 5.0 on 2023-12-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_centre_responsable_employe_centre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matierepremiere',
            old_name='nomM',
            new_name='nomMP',
        ),
        migrations.RenameField(
            model_name='matierepremiere',
            old_name='prix_achatM',
            new_name='prix_achatMP',
        ),
        migrations.RenameField(
            model_name='matierepremiere',
            old_name='prix_venteM',
            new_name='prix_venteMP',
        ),
    ]
