# Generated by Django 5.0 on 2023-12-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_centre_numeroc_absence_avancesalaire_pointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.centre'),
        ),
    ]
