# Generated by Django 5.0 on 2023-12-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employe_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='numeroC',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], unique=True),
        ),
    ]
