# Generated by Django 5.0 on 2023-12-27 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_centre_numeroc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employe'),
        ),
    ]
