# Generated by Django 5.0 on 2023-12-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pointage_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='pointage',
        ),
    ]
