# Generated by Django 5.0 on 2024-01-12 17:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_employe_points_delete_pointage'),
    ]

    operations = [
        migrations.CreateModel(
            name='venteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVente', models.DateTimeField(default=datetime.datetime.now)),
                ('qteVendu', models.IntegerField(default=0)),
                ('prixVente', models.FloatField(default=0, max_length=10)),
                ('montantVerse', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('produitVendu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='matierePremiere',
        ),
    ]
