# Generated by Django 5.0 on 2024-01-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_venteproduit_delete_matierepremiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_vente',
        ),
        migrations.AddField(
            model_name='produit',
            name='qte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='prixVente',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='qteVendu',
            field=models.IntegerField(),
        ),
    ]
