# Generated by Django 5.0 on 2024-01-14 20:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_produit_prix_achat_remove_produit_prix_vente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteproduit',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.centre'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='paiementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePaiement', models.DateTimeField(default=datetime.datetime.now)),
                ('montantPaiement', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
    ]
