# Generated by Django 5.0 on 2024-01-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_venteproduit_centre_paiementcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementcredit',
            name='montantPaiement',
            field=models.FloatField(null=True),
        ),
    ]
