# Generated by Django 5.0 on 2024-01-15 15:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_paiementcredit_montantpaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='matierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMP', models.CharField(max_length=50)),
                ('TypeMP', models.CharField(max_length=50)),
                ('Quantite', models.IntegerField()),
                ('Fournisseur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAchat', models.DateTimeField(default=datetime.datetime.now)),
                ('QteAchat', models.IntegerField(default=0)),
                ('prixAchat', models.FloatField(default=0)),
                ('montantTotal', models.FloatField(default=0)),
                ('montantverse', models.FloatField(default=0)),
                ('montantRestant', models.FloatField(default=0)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur')),
                ('matieresAchetes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='TransfertMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTransfert', models.DateTimeField(default=datetime.datetime.now)),
                ('QteTrf', models.IntegerField()),
                ('PrixUTA', models.FloatField(default=0)),
                ('CoutTrf', models.IntegerField(default=0)),
                ('MatieresTransferes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achat')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.centre')),
            ],
        ),
    ]
